import {notFound} from "next/navigation";
import type {Metadata} from "next";
import {ArrowLeft,ArrowRight,ExternalLink} from "lucide-react";
import {getNewsArticle,getNewsArticles} from "@/lib/news";
import SiteChrome from "@/components/site-chrome";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return getNewsArticles().map(article=>({slug:article.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const article=getNewsArticle(slug);if(!article)return{};return{title:article.title,description:article.description,alternates:{canonical:`/ai-news/${article.slug}`},robots:{index:true,follow:true},openGraph:{title:article.title,description:article.description,type:"article",publishedTime:article.publishedAt,modifiedTime:article.updatedAt||article.publishedAt}};}
export default async function NewsArticlePage({params}:Props){const {slug}=await params;const article=getNewsArticle(slug);if(!article)notFound();const site=process.env.NEXT_PUBLIC_SITE_URL||"https://speechpocket.vercel.app";const schema={"@context":"https://schema.org","@type":"NewsArticle",headline:article.title,description:article.description,datePublished:article.publishedAt,dateModified:article.updatedAt||article.publishedAt,author:{"@type":"Organization",name:article.author,url:site},publisher:{"@type":"Organization",name:"Voculo",url:site},mainEntityOfPage:`${site}/ai-news/${article.slug}`};return <SiteChrome active="news" actionHref="/tools" actionLabel="Browse tools" className="article-shell"><main className="article-main" id="main-content"><a className="article-back" href="/ai-news"><ArrowLeft size={16}/>All AI notes</a><article><header><div className="article-meta"><span>{article.category}</span><time dateTime={article.publishedAt}>{new Intl.DateTimeFormat("en",{dateStyle:"long",timeStyle:"short"}).format(new Date(article.publishedAt))}</time></div><h1>{article.title}</h1><p className="article-dek">{article.dek}</p><div className="byline">By {article.author}{article.sourceEventDate&&<> · Event date: {article.sourceEventDate}</>}</div></header><section className="takeaway-box"><strong>What matters</strong><ul>{article.takeaways.map(item=><li key={item}>{item}</li>)}</ul></section>{article.sections.map(section=><section className="article-section" key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}</section>)}<section className="article-sources"><h2>Sources</h2><p>Voculo used these pages to verify the facts in this report.</p><ul>{article.sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}<ExternalLink size={14}/></a></li>)}</ul></section></article><aside className="article-cta"><span>Try Voculo</span><h2>Turn a recording into a useful result.</h2><p>Transcribe, label speakers, analyze audio, or generate a short voice track.</p><a href="/tools">Open audio tools <ArrowRight size={17}/></a></aside></main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replaceAll("<","\\u003c")}}/></SiteChrome>}
