import type {Metadata} from "next";
import {ArrowRight,Clock3,Sparkles} from "lucide-react";
import {getNewsArticles} from "@/lib/news";

export const metadata:Metadata={title:"AI tools news",description:"Verified AI product launches, updates, comparisons, and practical analysis from SpeechPocket.",alternates:{canonical:"/ai-news"},robots:{index:true,follow:true},openGraph:{title:"AI tools news | SpeechPocket",description:"Verified AI product launches, updates, comparisons, and practical analysis.",type:"website"}};

export default function NewsIndex(){
 const articles=getNewsArticles();
 return <div className="site-shell news-shell"><header className="site-header"><a href="/" className="brand"><span className="brand-mark"><i/><i/><i/><i/></span><span className="brand-copy"><b>SpeechPocket</b><small>Speech intelligence tools</small></span></a><nav className="top-nav"><a href="/">Tools</a><a href="/ai-news" aria-current="page">AI news</a><a href="/privacy">Privacy</a></nav><a className="header-action" href="/en/audio-language-detector">Try a tool <ArrowRight size={16}/></a></header><main className="news-main"><section className="news-hero"><div><div className="eyebrow"><span className="eyebrow-dot"/>Fresh, source-checked coverage</div><h1>AI tools news,<br/><span>without the recycled hype.</span></h1><p>Product launches, important updates, and practical analysis for people who actually use AI software.</p></div><aside><Sparkles/><strong>Up to 3 useful stories daily</strong><span>Every article must pass source, duplication, and originality checks before publication.</span></aside></section><div className="news-filter"><span>Latest reports</span><a href="/rss.xml">RSS feed</a></div>{articles.length?<section className="news-grid">{articles.map((article,index)=><article className={index===0?"featured":""} key={article.slug}><a href={`/ai-news/${article.slug}`}><div className="news-card-meta"><span>{article.category}</span><time dateTime={article.publishedAt}><Clock3 size={14}/>{new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(article.publishedAt))}</time></div><h2>{article.title}</h2><p>{article.description}</p><span className="read-link">Read analysis <ArrowRight size={16}/></span></a></article>)}</section>:<section className="news-empty"><Sparkles/><h2>The newsroom is connected.</h2><p>The first verified AI-tool story will appear after the scheduled publishing workflow completes. SpeechPocket will not publish filler just to satisfy a quota.</p><a href="/en/audio-language-detector">Use the audio language detector <ArrowRight size={16}/></a></section>}</main><footer className="site-footer page-frame"><a href="/" className="footer-brand">SpeechPocket</a><p>Free speech intelligence tools and practical AI news.</p><a href="/rss.xml">RSS</a><a href="/privacy">Privacy</a></footer></div>;
}
